version: '3.3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - '5434:5432'
  mongo:
    image: 'mongo:7'
    restart: always
    volumes:
      - ./data/mongo:/data/db
    expose:
      - 27017
    ports:
      - '27020:27017'
